mongodb:
  image: mongo:latest
  username: root
  password: 123456a
  database: lib_db
  localPort: 7017
  dockerPort: 27017

bookappbackend:
  image: pdelebarre/bookappbackend:latest
  localPort: 8080
  dockerPort: 6868

volumes:
  db:
    enabled: true
    
spring:
  devtools:
    add-properties: false

