apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-username: {{ .Values.mongodb.username | b64enc | quote }}
  mongodb-password: {{ .Values.mongodb.password | b64enc | quote }}
