apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
    - port: {{ .Values.mongodb.localPort }}
      targetPort: {{ .Values.mongodb.dockerPort }}
  selector:
    app: mongodb

---
apiVersion: v1
kind: Service
metadata:
  name: bookappbackend
spec:
  type: NodePort
  ports:
    - port: {{ .Values.bookappbackend.localPort }}
      targetPort: {{ .Values.bookappbackend.dockerPort }}
      nodePort: 30068  # Explicitly set a NodePort within the allowed range (30000-32767)
  selector:
    app: bookappbackend
