apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
    - port: {{ .Values.mongodb.localPort }}
      targetPort: {{ .Values.mongodb.dockerPort }}
  selector:
    app: mongodb

---
apiVersion: v1
kind: Service
metadata:
  name: bookappbackend
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.bookappbackend.localPort }}
      targetPort: {{ .Values.bookappbackend.dockerPort }}
  selector:
    app: bookappbackend
